import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';import assert from 'node:assert/strict';import {previewServer} from '../tools/preview-server.mjs';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.JT_NODE_MODULES+'/playwright');
const out=new URL('../../validation/ui-1111/',import.meta.url);mkdirSync(out,{recursive:true});
const server=await previewServer(),browser=await chromium.launch({headless:true,channel:'msedge'}),report={simulatedNative:true,humanMicrophone:false,formats:[],passed:false};let page;
try{for(const [width,height,scale] of [[412,915,1],[360,800,1],[320,640,1],[844,390,1],[412,915,1.6]]){
 const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,hasTouch:true});page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({scale})=>{window.calls=[];window.saved={};window.AndroidTrainer={getProfile:()=>JSON.stringify(window.seed??{}),saveProfile:t=>{window.saved=JSON.parse(t);return true;},getCapabilities:()=>JSON.stringify({native:true,models:true,version:'test',device:'simulated browser',recognizer:'sensevoice',testModels:{}}),stopAudio:()=>{},stopRecording:cancel=>calls.push({kind:'stop',cancel}),speak:(text,sid,speed,id)=>calls.push({kind:'speak',text,id}),recordComparison:(id,short)=>calls.push({kind:'comparison',id,short}),recordKana:id=>calls.push({kind:'record',id}),record:id=>calls.push({kind:'record',id}),exportSpeechReport:text=>calls.push({kind:'export',text})};document.addEventListener('DOMContentLoaded',()=>{document.documentElement.style.fontSize=(16*scale)+'px';});},{scale});
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForSelector('html[data-ready=true]');
 await page.locator('[data-nav=daily]').first().click();assert.equal(await page.locator('#daily-intro').count(),1);
 await page.screenshot({path:fileURLToPath(new URL(`daily-${width}-${height}-${scale}.png`,out))});
 await page.locator('#daily-intro').click();await page.locator('#daily-next').click();await page.locator('#daily-intro').click();await page.locator('#daily-next').click();assert.equal(await page.locator('#daily-intro').count(),0);assert.equal(await page.evaluate(()=>saved.xp),0);assert.equal(await page.evaluate(()=>saved.completed.length),0);
 for(const skill of ['listen','write','speak']){
  await page.evaluate(skill=>{const date=new Date().toLocaleDateString('sv-SE');JTNative('profileImported',{xp:20,completed:['0:0'],course_revision:11,adaptive:{daily:{date,tasks:[{id:'ui-'+skill,card:'0:0:0',skill}],done:[]}}});},skill);await page.locator('[data-nav=daily]').first().click();
  if(skill==='write'){await page.locator('#daily-input').fill('oo');await page.locator('#daily-check').click();assert.equal(await page.locator('#daily-next').count(),0);await page.locator('#daily-input').fill('a');await page.locator('#daily-check').click();assert.equal(await page.evaluate(()=>saved.adaptive.skills['0:0:0'].write.right),0);}
  else{if(skill==='listen'){await page.getByRole('button',{name:'Laut a',exact:true}).click();assert.equal(await page.locator('#daily-next').count(),0);}await page.locator('#daily-audio').click();await page.evaluate(()=>JTNative('audioDone',{request:calls.filter(c=>c.kind==='speak').at(-1).id}));if(skill==='listen')await page.getByRole('button',{name:'Laut a',exact:true}).click();else{await page.locator('#daily-record').click();await page.evaluate(()=>{const id=calls.at(-1).id;JTNative('recording',{request:id});JTNative('speechResult',{request:id,text:'あ',shortKana:true,audioQualified:true});JTNative('speechResult',{request:id,text:'あ',shortKana:true,audioQualified:true});});assert.equal(await page.evaluate(()=>saved.adaptive.skills['0:0:0'].speak.attempts),1);}}
  assert.equal(await page.locator('#daily-next').count(),1);assert.equal(await page.evaluate(()=>saved.xp),20);await page.locator('#daily-next').click();
 }
 await page.locator('[data-nav=practice-lab]').click();assert.equal(await page.locator('[data-story]:disabled').count(),4);await page.locator('[data-trace]').first().click();const box=await page.locator('#trace-pad').boundingBox();await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();await page.mouse.move(box.x+80,box.y+110,{steps:10});await page.mouse.up();await page.locator('#trace-guide').click();await page.screenshot({path:fileURLToPath(new URL(`trace-${width}-${height}-${scale}.png`,out))});await page.locator('#practice-back').click();
 // Separate older profile, retaining its IDs and XP; no private learner data.
 await page.evaluate(()=>JTNative('profileImported',{xp:777,completed:['v11:dialog-cafe'],course_revision:11,last_lesson:{key:'v11:dialog-cafe',card:2}}));await page.locator('[data-page=more]').click();await page.locator('[data-nav=practice-lab]').click();await page.locator('[data-story="practice:cafe"]').click();await page.locator('[data-story-answer="1"]').click();assert.match(await page.locator('#story-status').innerText(),/vollständig/);await page.locator('#story-play').click();await page.evaluate(()=>JTNative('audioDone',{request:calls.filter(c=>c.kind==='speak').at(-1).id}));await page.locator('[data-story-answer="0"]').click();assert.match(await page.locator('#story-status').innerText(),/Achte/);await page.locator('[data-story-answer="1"]').click();await page.locator('#story-next').click();await page.locator('[data-story-answer="2"]').click();await page.locator('#story-next').click();assert.equal(await page.evaluate(()=>saved.adaptive.milestones['practice:cafe'].mode),'supported');assert.equal(await page.evaluate(()=>saved.xp),777);
 await page.locator('[data-page=more]').click();await page.locator('[data-nav=speech-lab]').click();await page.locator('#lab-record').click();const req=await page.evaluate(()=>calls.at(-1));assert.deepEqual(Object.keys(req).sort(),['id','kind','short']);await page.evaluate(id=>{JTNative('recording',{request:id});JTNative('recognizing',{request:id});JTNative('speechResult',{request:id,text:'あ',comparison:true,audioQualified:true,results:[{model:'sensevoice',text:'あ',loadMs:10,decodeMs:20}]});JTNative('speechResult',{request:id,text:'あ',results:[]});},req.id);await page.locator('#lab-quality').selectOption('as_requested');await page.screenshot({path:fileURLToPath(new URL(`speech-${width}-${height}-${scale}.png`,out))});await page.locator('#lab-export').click();const result=await page.evaluate(()=>JSON.parse(calls.at(-1).text));assert.equal(result.attempts.length,1);assert.equal(result.attempts[0].confirmation,'as_requested');assert.equal(result.attempts[0].results[0].match,true);assert.equal(result.audio_included,false);assert.equal(await page.evaluate(()=>saved.xp),777);
 await page.locator('#lab-next').click();await page.locator('#lab-record').click();const stale=await page.evaluate(()=>calls.at(-1).id);await page.locator('[data-page=more]').click();await page.evaluate(id=>JTNative('speechResult',{request:id,text:'い',results:[]}),stale);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('jt-speech-trial-v1')).length),1);
 await page.locator('[data-nav=talk]').click();await page.locator('[data-talk-scene=restaurant]').click();assert.equal(await page.locator('#talk-prep-next').count(),1);for(let i=0;i<6;i++)await page.locator('#talk-prep-next').click();assert.equal(await page.locator('#talk-prep-next').count(),0);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(errors,[]);report.formats.push({width,height,scale,passed:true});await context.close();
}report.passed=true;}catch(e){if(page)await page.screenshot({path:fileURLToPath(new URL('failure.png',out))});throw e;}finally{writeFileSync(new URL('report.json',out),JSON.stringify(report,null,2));await browser.close();server.close();}console.log(report);
