import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {previewServer} from '../tools/preview-server.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.JT_NODE_MODULES+'/playwright');
const out=new URL('../../validation/recovery-1115/',import.meta.url);mkdirSync(out,{recursive:true});
const course=JSON.parse(readFileSync(new URL('../../data/course.json',import.meta.url),'utf8'));
const long=course.units.flatMap(u=>u.lessons).find(l=>l.id==='v11:long-vowels');
const server=await previewServer(),browser=await chromium.launch({headless:true,channel:'msedge'});
const report={passed:false,simulatedNative:true,humanMicrophone:false,formats:[],views:0};let page;
try{for(const [width,height,scale] of [[393,780,1],[393,744,1],[320,640,1],[393,780,1.2],[412,915,1.6],[844,390,1]]){
 const ctx=await browser.newContext({viewport:{width,height},hasTouch:true});page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({scale})=>{window.calls=[];window.AndroidTrainer={getProfile:()=>{const seed=localStorage.getItem('seed');if(seed){localStorage.removeItem('seed');localStorage.setItem('p',seed);}return localStorage.getItem('p')??'{}';},saveProfile:s=>(localStorage.setItem('p',s),true),getCapabilities:()=>'{"native":true,"models":true}',speak:(t,s,v,id)=>calls.push({kind:'audio',id}),record:id=>calls.push({kind:'speech',id}),recordKana:id=>calls.push({kind:'speech',id}),stopAudio(){},stopRecording(){}};document.addEventListener('DOMContentLoaded',()=>document.documentElement.style.fontSize=16*scale+'px');},{scale});
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForSelector('html[data-ready=true]');
 async function open(key,index,phase){await page.evaluate(({key,index,phase})=>localStorage.setItem('seed',JSON.stringify({completed:[],xp:45,teacher_id:'ren',course_revision:11,last_lesson:{key,card:index},legacy_unlocked:[key],lesson_sessions:{[key]:{flow_revision:2,index,phase,mode:'learn',passed:['speak','meaning','listen','build','write'].slice(0,['speak','meaning','listen','build','write','apply'].indexOf(phase))}}})),{key,index,phase});await page.reload();await page.waitForSelector('html[data-ready=true]');await page.locator('#hero-resume').click();if(await page.locator('.focus-sheet:not([hidden])').count())await page.locator('.focus-sheet-close').click();await page.waitForTimeout(160);}
 async function hit(selector){return page.locator(selector).evaluate(n=>{const r=n.getBoundingClientRect(),at=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return r.width>0&&r.height>0&&r.left>=-1&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1&&(at===n||n.contains(at));});}
 async function capture(name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);report.views++;await page.screenshot({path:fileURLToPath(new URL(`${name}-${width}-${height}-${scale}.png`,out))});}
 async function taskChoice(value){await page.waitForTimeout(150);const index=await page.locator('[data-choice]').evaluateAll((nodes,value)=>nodes.find(n=>n.textContent===value)?.dataset.choice,value);assert.notEqual(index,undefined,value);const selector=`[data-choice="${index}"]`;for(let i=0;i<20;i++){if(await hit(selector)){await page.locator(selector).click();return;}const pager=page.locator('.focus-page-nav');assert.equal(await pager.isVisible(),true,'offscreen choice needs visible pagination');assert.equal(await pager.locator('button').last().isEnabled(),true,'choice must be reachable');await pager.locator('button').last().click();await page.waitForTimeout(80);}throw Error('unreachable choice');}
 await open('v11:long-vowels',2,'apply');const seen=new Set();
 for(let i=0;i<20;i++){const choices=page.locator('[data-choice]');for(let n=0;n<await choices.count();n++){const b=choices.nth(n);if(await b.evaluate(n=>{const r=n.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return r.width>0&&r.height>0&&(h===n||n.contains(h));}))seen.add(await b.textContent());}const next=page.locator('.focus-page-nav button').last();if(!await page.locator('.focus-page-nav').isVisible()||await next.isDisabled())break;await next.click();await page.waitForTimeout(80);}
 assert.equal(seen.size,4,'all four whole choices reachable');assert.equal(await page.locator('.answer-count').textContent(),'Wähle eine von 4 Antworten.');
 if(await page.locator('.focus-page-nav').isVisible())while(await page.locator('.focus-page-nav button').first().isEnabled()){await page.locator('.focus-page-nav button').first().click();await page.waitForTimeout(80);}
 await taskChoice('Eine Tante; das a in ba bleibt kurz.');await page.waitForTimeout(150);assert.equal(await hit('#defer-task'),true,'wrong answer can be deferred without scrolling');assert.equal(await page.locator('[data-choice]').count(),4);assert.equal(await page.locator('.answer-count').textContent(),'Wähle eine von 4 Antworten.');await capture('four-answers-after-error');
 await page.getByRole('button',{name:'ⓘ Rückmeldung',exact:true}).click();assert.equal(await page.locator('.focus-sheet:not([hidden])').isVisible(),true);await page.locator('.focus-sheet-close').click();
 await page.getByRole('button',{name:'ⓘ Warum?',exact:true}).click();let sheets=0;for(let i=0;i<20;i++){sheets++;await page.waitForTimeout(80);const next=page.locator('.focus-sheet-actions button').last();if(await next.isDisabled())break;assert.equal(await hit('.focus-sheet-actions button:last-child'),true);await next.click();}assert.ok(sheets>=1&&sheets<20);await page.locator('.focus-sheet-close').click();assert.equal(await hit('#defer-task'),true);
 await page.locator('#defer-task').click();assert.equal(await page.locator('#step-count').textContent(),'Schritt 1/6');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('p')));assert.equal(saved.lesson_sessions['v11:long-vowels'].retry_tasks[0].phase,'apply');assert.equal(saved.completed.length,0);assert.equal(saved.xp,45);
 await open('0:1',2,'speak');await page.locator('#hear-normal').click();await page.evaluate(()=>JTNative('audioDone',{request:calls.at(-1).id}));
 for(let i=0;i<3;i++){await page.locator('#record').click();await page.evaluate(()=>JTNative('speechError',{request:calls.at(-1).id,message:'Technischer Testfehler'}));await page.waitForTimeout(80);if(i<2)assert.equal(await page.locator('#speech-alternative').count(),0);}
 await page.waitForTimeout(150);assert.equal(await hit('#speech-alternative'),true,'after three failures support is visible without scrolling');await capture('three-attempts');
 const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('p')));await page.reload();await page.waitForSelector('html[data-ready=true]');await page.locator('#hero-resume').click();await page.waitForTimeout(150);assert.equal(await hit('#speech-alternative'),true,'support survives restart');await page.locator('#speech-alternative').click();assert.equal(await hit('[data-support-choice]:first-child'),true);await capture('speech-choice');
 const target=await page.locator('.support-prompt').textContent();assert.ok(target.length>10);
 await page.locator('#speech-close').click();assert.equal(await hit('#speech-alternative'),true);assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('p')))).xp,before.xp);
 await page.locator('#speech-alternative').click();await page.locator('[data-support-choice]:not([data-support-choice="0:1:2"])').first().click();await page.locator('#speech-confirm').click();assert.equal(await page.locator('#advance').isVisible(),false);assert.equal(await page.locator('.speech-alternative').isVisible(),true);
 await page.locator('[data-support-choice="0:1:2"]').click();assert.equal(await page.locator('#advance').isVisible(),false,'choice alone does not pass');await page.locator('#speech-confirm').click();assert.equal(await hit('#advance'),true);assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('p')))).xp,45);await page.locator('#advance').click();assert.equal(await page.locator('#step-count').textContent(),'Schritt 2/6');
 await open('v11:long-vowels',4,'apply');await taskChoice('Er ist klein.');await page.locator('#defer-task').click();assert.equal(await page.locator('#step-count').textContent(),'Fehlerwiederholung · 1/1');await capture('original-task-repeated');await page.reload();await page.waitForSelector('html[data-ready=true]');await page.locator('#hero-resume').click();assert.equal(await page.locator('#step-count').textContent(),'Fehlerwiederholung · 1/1');await taskChoice('Er ist groß; oo und ii werden länger gehalten.');await page.locator('#advance').click();
 let completed=false;for(let i=0;i<12;i++){const p=await page.evaluate(()=>JSON.parse(localStorage.getItem('p'))),s=p.lesson_sessions['v11:long-vowels'];assert.equal(s.mode,'recap');assert.equal(p.xp,45);await taskChoice(long.cards[s.index].de);await page.locator('#advance').click();if(await page.locator('.completion').count()){completed=true;break;}}
 assert.equal(completed,true);const ended=await page.evaluate(()=>JSON.parse(localStorage.getItem('p')));assert.equal(ended.xp,45+(long.xp??20));assert.deepEqual(ended.completed,['v11:long-vowels']);assert.deepEqual(errors,[]);
 report.formats.push({width,height,scale,fourAnswers:seen.size,helpPages:sheets,speechSupportVisible:true,restartPreserved:true});await ctx.close();
}report.passed=true;}catch(e){if(page)await page.screenshot({path:fileURLToPath(new URL('failure.png',out))});throw e;}
finally{writeFileSync(new URL('report.json',out),JSON.stringify(report,null,2));await browser.close();server.close();}
console.log(JSON.stringify(report));
