import {recordAttempt} from './adaptive.mjs';
export function createPracticeUI({data,state,store,course,play,stopMedia,navigate,render,esc,toast}){
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 let story=null,index=0,heard=false,help=false,helpUsed=false,success=false,message='',audioId=null,trace=null,strokes=[],guide=true;
 const known=key=>store.data.completed.includes(key)||course.byKey.get(key)?.cards.every((_,i)=>store.data.adaptive.introduced.includes(`${key}:${i}`));
 function hub(){const kana=course.available().filter(c=>/^[ぁ-んァ-ヶ]$/u.test(c.jp));
  return `<h1>Hörsituationen & Zeichen</h1><p class="sub">Wende deinen Wortschatz in kleinen Situationen an. Kurslektionen und XP bleiben erhalten.</p><section class="card"><h2>Das kannst du schon üben</h2><div class="practice-list">${data.stories.map(s=>`<button class="ghost" data-story="${s.id}" ${known(s.lesson)?'':'disabled'}><strong>${esc(s.title)}</strong><span>${store.data.adaptive.milestones[s.id]?.mode==='listening'?'✓ Durch Hörfragen belegt':known(s.lesson)?'Bekannte Wörter · 2 Fragen':`Zuerst: ${esc(course.byKey.get(s.lesson).title)}`}</span></button>`).join('')}</div></section><section class="card"><h2>Zeichen nachzeichnen</h2><p>${esc(data.trace_note)}</p><div class="toolbar">${kana.slice(0,80).map(c=>`<button class="ghost" data-trace="${esc(c.key)}" lang="ja">${esc(c.jp)}</button>`).join('')}</div></section>`;
 }
 function view(){if(trace)return traceView();if(!story)return hub();const l=course.byKey.get(story.lesson),q=story.questions[index];
  if(!q)return `<section class="card daily-card"><span class="pill success">Situation geübt</span><h1>${esc(story.title)}</h1><p>${helpUsed?'Mit Lesehilfe bearbeitet. Beim nächsten Versuch kannst du dich ganz aufs Hören konzentrieren.':'Du hast beide Hörfragen mit bekanntem Wortschatz gelöst.'}</p><button class="primary wide" id="practice-back">Andere Situation</button></section>`;
  return `<div class="daily-layout"><div class="lesson-header"><button class="back-button" id="practice-back" aria-label="Zurück">‹</button><div><h1>${esc(story.title)}</h1><p class="sub">Frage ${index+1} / ${story.questions.length}</p></div></div><section class="card daily-card"><h2>Höre den kurzen Dialog.</h2><div class="row"><button class="primary" id="story-play">▷ Anhören</button><button class="ghost" id="story-slow">▷ Langsam</button></div><button class="ghost small" id="story-help" aria-expanded="${help}">Lesung & Bedeutung anzeigen</button>${help?`<div class="info">${l.cards.map(c=>`<p lang="ja">${esc(c.jp)}</p><p>${esc(c.romaji)} · ${esc(c.de)}</p>`).join('')}</div>`:''}<h2>${esc(q.prompt)}</h2><div class="options">${q.options.map((a,i)=>`<button class="option" data-story-answer="${i}" ${success?'disabled':''}>${esc(a)}</button>`).join('')}</div><p class="feedback" id="story-status" role="status">${esc(message)}</p></section>${success?'<div class="daily-footer"><button class="primary wide" id="story-next">Weiter →</button></div>':''}</div>`;
 }
 function traceView(){return `<section class="card daily-card"><button class="ghost small" id="practice-back">‹ Zurück</button><h1>Zeichne ${esc(trace.jp)} nach</h1><p>${esc(trace.romaji)} · ${esc(data.trace_note)}</p><canvas class="trace-canvas" id="trace-pad" width="600" height="600" aria-label="Zeichenfläche"></canvas><div class="toolbar"><button class="ghost" id="trace-guide">Vorlage ${guide?'ausblenden':'einblenden'}</button><button class="ghost" id="trace-clear">Neu zeichnen</button></div><p class="sub">Vergleiche die Form selbst mit der Vorlage. Diese Übung schaltet keine Lektion frei.</p></section>`;}
 function draw(){const canvas=$('#trace-pad');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,600,600);ctx.strokeStyle='#ced9e4';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(300,0);ctx.lineTo(300,600);ctx.moveTo(0,300);ctx.lineTo(600,300);ctx.stroke();if(guide){ctx.fillStyle='#b2c7db';ctx.font='440px "Noto Sans JP", sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(trace.jp,300,320);}ctx.strokeStyle='#126da2';ctx.lineWidth=10;ctx.lineCap='round';ctx.lineJoin='round';for(const stroke of strokes){ctx.beginPath();stroke.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();}}
 function bind(){if(state.page!=='practice-lab')return;
  $$('[data-story]').forEach(b=>b.onclick=()=>{const s=data.stories.find(x=>x.id===b.dataset.story);if(!known(s.lesson))return;story=s;trace=null;index=0;heard=false;help=false;helpUsed=false;success=false;message='';render();});
  $$('[data-trace]').forEach(b=>b.onclick=()=>{trace=course.cards.find(c=>c.key===b.dataset.trace);strokes=[];guide=true;render();});
  if($('#practice-back'))$('#practice-back').onclick=()=>{stopMedia();story=null;trace=null;audioId=null;render();};
  for(const [id,slow] of [['story-play',false],['story-slow',true]])if($('#'+id))$('#'+id).onclick=()=>{play(course.byKey.get(story.lesson).cards.map(c=>c.jp.replace(/[。]+$/u,'')+'。').join(' '),false,slow);audioId=state.audio?.id;};
  if($('#story-help'))$('#story-help').onclick=()=>{help=!help;helpUsed||=help;render();};
  $$('[data-story-answer]').forEach(b=>b.onclick=()=>{if(success)return;if(!heard&&!help){message='Höre den Dialog zuerst vollständig oder öffne bewusst die Lesehilfe.';render();return;}const q=story.questions[index],ok=q.options[+b.dataset.storyAnswer]===q.correct,c=course.byKey.get(story.lesson).cards[q.evidence];
   recordAttempt(store.data,`${story.lesson}:${q.evidence}`,heard&&!helpUsed?'listen':'read',ok,helpUsed);store.save();success=ok;message=ok?'Richtig.':`Diese Antwort passt nicht. Achte auf: ${c.jp} (${c.romaji}) – ${c.de}.`;if(!ok)helpUsed=true;render();});
  if($('#story-next'))$('#story-next').onclick=()=>{index++;success=false;message='';if(index===story.questions.length){const old=store.data.adaptive.milestones[story.id];store.data.adaptive.milestones[story.id]={mode:old?.mode==='listening'||!helpUsed?'listening':'supported',completedAt:new Date().toISOString()};store.touch();store.save();}render();};
  if($('#trace-pad')){draw();const c=$('#trace-pad');let active=false;const point=e=>{const r=c.getBoundingClientRect();return [Math.max(0,Math.min(600,(e.clientX-r.left)/r.width*600)),Math.max(0,Math.min(600,(e.clientY-r.top)/r.height*600))];};c.onpointerdown=e=>{active=true;c.setPointerCapture(e.pointerId);strokes.push([point(e)]);draw();};c.onpointermove=e=>{if(active){strokes.at(-1).push(point(e));draw();}};c.onpointerup=c.onpointercancel=()=>{active=false;};$('#trace-guide').onclick=()=>{guide=!guide;render();};$('#trace-clear').onclick=()=>{strokes=[];draw();};}
 }
 function event(type,d){if(state.page==='practice-lab'&&type==='audioDone'&&d.request===audioId){heard=true;message='Dialog gehört. Beantworte die Frage.';if($('#story-status'))$('#story-status').textContent=message;}return false;}
 return {view,bind,event,reset:()=>{story=null;trace=null;audioId=null;}};
}
