/* Authored offline scene. Own linguistic review, human Japanese review pending. */
const line=(jp,romaji,de)=>({jp,romaji,de});
const route=(id,pattern,next,slots={})=>({id,pattern,next,slots});
const food=(words)=>new RegExp(`^(?:${words})(?:を)?(?:ください|お願いします|おねがいします|にします)$`,'u');
export const RESTAURANT={id:'restaurant',title:'Im Restaurant bestellen',icon:'🍜',role:'Im Restaurant',goal:'Bestelle ein Gericht und ein Getränk, bitte um die Rechnung und bezahle.',start:'food',preparation:[
 {...line('ご注文はお決まりですか。','gochūmon wa okimari desu ka.','Haben Sie sich entschieden?'),why:'Eine höfliche Frage im Service. Du musst diese Form zunächst nur verstehen.'},
 {...line('うどんをください。','udon o kudasai.','Udon, bitte.'),why:'Mit Gegenstand + をください bittest du um etwas. Auch そば (soba) und カレー (karē, Curry) sind in dieser Szene möglich.'},
 {...line('お飲み物はいかがですか。','onomimono wa ikaga desu ka.','Möchten Sie etwas trinken?'),why:'Auch hier spricht der Service höflich. 水 (mizu) ist Wasser, お茶 (ocha) ist Tee.'},
 {...line('水をお願いします。','mizu o onegai shimasu.','Wasser, bitte.'),why:'Gegenstand + をお願いします ist eine weitere höfliche Bitte. Du kannst in der Szene auch Tee wählen.'},
 {...line('お会計をお願いします。','okaikei o onegai shimasu.','Die Rechnung, bitte.'),why:'お会計 (okaikei) bezeichnet hier das Bezahlen beziehungsweise die Rechnung.'},
 {...line('カードで払えますか。','kādo de haraemasu ka.','Kann ich mit Karte bezahlen?'),why:'Mit で nennst du das Zahlungsmittel. 現金 (genkin) bedeutet Bargeld. 払えますか fragt, ob Bezahlen möglich ist.'}
 ],nodes:{
 food:{say:line('いらっしゃいませ。ご注文はお決まりですか。','irasshaimase. gochūmon wa okimari desu ka.','Willkommen. Haben Sie sich entschieden?'),cue:'Bestelle Udon, Soba oder Curry. Nutze eine höfliche Bitte.',hints:[line('うどんをください。','udon o kudasai.','Udon, bitte.'),line('そばをお願いします。','soba o onegai shimasu.','Soba, bitte.'),line('カレーをください。','karē o kudasai.','Curry, bitte.')],routes:[route('udon',food('うどん'),'drink',{food:'うどん',roman:'udon'}),route('soba',food('そば'),'drink',{food:'そば',roman:'soba'}),route('curry',food('かれー'),'drink',{food:'カレー',roman:'karē'})]},
 drink:{say:s=>line(`${s.food}ですね。お飲み物はいかがですか。`,`${s.roman} desu ne. onomimono wa ikaga desu ka.`,'Gern. Möchten Sie etwas trinken?'),cue:'Bestelle Wasser oder Tee.',hints:[line('水をお願いします。','mizu o onegai shimasu.','Wasser, bitte.'),line('お茶をください。','ocha o kudasai.','Tee, bitte.')],routes:[route('water',food('水|みず|お水|おみず'),'bill'),route('tea',food('お茶|おちゃ'),'bill')]},
 bill:{say:line('ありがとうございます。どうぞごゆっくり。','arigatō gozaimasu. dōzo goyukkuri.','Vielen Dank. Lassen Sie sich Zeit.'),cue:'Stell dir vor, du hast aufgegessen. Bitte nun um die Rechnung.',hints:[line('お会計をお願いします。','okaikei o onegai shimasu.','Die Rechnung, bitte.')],routes:[route('bill',/^(?:お会計|おかいけい|会計|かいけい)(?:を)?(?:お願いします|おねがいします)$/u,'payment')]},
 payment:{say:line('お支払いはどうなさいますか。','oshiharai wa dō nasaimasu ka.','Wie möchten Sie bezahlen?'),cue:'Sage, ob du bar oder mit Karte zahlen möchtest. Du kannst auch zuerst nach Kartenzahlung fragen.',hints:[line('現金でお願いします。','genkin de onegai shimasu.','Bar, bitte.'),line('カードで払えますか。','kādo de haraemasu ka.','Kann ich mit Karte bezahlen?'),line('カードでお願いします。','kādo de onegai shimasu.','Mit Karte, bitte.')],routes:[route('cash',/^(?:現金|げんきん)で(?:お願いします|おねがいします|払います|はらいます)$/u,'done'),route('card-question',/^かーどで(?:払えます|はらえます|いいです)か$/u,'card-ok'),route('card',/^かーどで(?:お願いします|おねがいします|払います|はらいます)$/u,'done')]},
 'card-ok':{say:line('はい、カードで払えます。','hai, kādo de haraemasu.','Ja, Sie können mit Karte bezahlen.'),cue:'Bestätige die Kartenzahlung oder entscheide dich doch für Bargeld.',hints:[line('では、カードでお願いします。','dewa, kādo de onegai shimasu.','Dann mit Karte, bitte.'),line('現金でお願いします。','genkin de onegai shimasu.','Bar, bitte.')],routes:[route('card',/^(?:では)?かーどで(?:お願いします|おねがいします)$/u,'done'),route('cash',/^(?:現金|げんきん)で(?:お願いします|おねがいします)$/u,'done')]},
 done:{done:true,say:line('ありがとうございました。またお越しください。','arigatō gozaimashita. mata okoshi kudasai.','Vielen Dank. Kommen Sie gerne wieder.')}
 }};
