"""Reproducible package-04 findings, stable card identifiers and review limits."""
import re
from tools.upgrade_package4 import GUIDES, APPLICATIONS, READ_FEEDBACK

def report(raw, order):
    out=['# Paket 04 Zeit Verabredungen und spätere Anwendung',
      '25 erstmals vertiefte bestehende Lektionen / 123 Karten. Dazu eine ausdrücklich abgegrenzte Vorbereitungskorrektur an der bereits in Paket 03 geprüften Karte `12:0:4`. Sie wird nicht erneut gezählt. Zusammen 105 eindeutige Lektionen / 501 Karten selbst sprachlich durchgesehen; 45 Lektionen / 179 Karten bleiben einzeln offen. Kurs: 150 Lektionen / 680 Karten / 565 explizite Sprechziele. Keine zusätzliche Lektion nötig.',
      '## Ausgangspunkt und Auswahl',
      'Ausgangsstand `21de74cfd5cde7ba8d77cda00c877ca590d90dbf`, Testversion 11.0.5. Die konkreten 80 früheren Lektions-IDs, alle 150 Lektionshashes, 680 Kartenidentitäten, Reihenfolge und geschützte Programmdateien stehen im unveränderten Ausgangsvertrag `tests/fixtures/package03-contract.json`. Auswahl aus den übrigen 70 Einheiten: zuerst Personen-/Zeit-/Kalenderangaben (47–53), dann Häufigkeit (59), Jahreszeiten/Wetter/Befinden (82–85), Freizeit/Einladen/Verbgrundlagen (88–94), Termine/Nachrichten (126/129) und Dialog/Lesetexte (134/137–139). Der Zusammenhang führt von Zeitangaben über Handlungen zu einer vereinbarten oder noch offenen Verabredung und einer Rückschau. Keine bloße Auswahl der nächsten 25 Positionen.',
      'Die vorhandenen Erklärungen und Beispiele waren vielfach brauchbar. Es fehlten bei den ausgewählten 25 Einheiten explizite Vorwissensbezüge, zusammenhängende Vorbereitung der früher benötigten Beispielwörter sowie Begründungen für die tatsächlichen falschen Anwendungsantworten. Konkrete Verwechslungen: Personen/Stückzahlen/Alter, Uhrzeit/Dauer, halb drei gegenüber drei Uhr dreißig, Kalendertag gegenüber Lebensalter, Einladung gegenüber Verneinung, Terminwunsch gegenüber Bestätigung und bedingter Plan gegenüber sicherem Ereignis. 75 eigene Lernhilfe-Absätze und 37 gezielte neue/überarbeitete Anwendungsfragen bearbeiten diese Fälle. Neun bereits passende Leseverständnisfragen bleiben erhalten und bekommen einzeln formulierte Fehlantwortbegründungen; auf allen 123 Karten sind die tatsächlichen Anwendungsdistraktoren erklärt.',
      '## Bestand und gesonderte Zahlenkorrektur',
      '124 nicht ausgewählte Lektionen, darunter 79 der bisherigen 80, bleiben als vollständige Objekte unverändert. In `12:0` bleibt ebenfalls alles unverändert außer `cards[4].detail`: drei Zweiergruppen für 5/6, 7/8 und 9/10 mit freiwilligen Selbstabrufen und eine konkrete Anwendungsfrage nach der Zahl direkt nach sieben. Die bisherige Sammelkarte verlangt sechs Formen auf einmal; ihre ursprüngliche Erklärung hatte keine Teile oder kleineren Beispiele. Die bestehende Erklärungs-/Hilfeansicht kann die Gruppen darstellen, sodass keine neue Oberfläche erforderlich ist.',
      'Die ganze Reihe bleibt als Sprech-, Bau- und Schreibziel erhalten. Hilfe vergibt keine Freigabe oder XP; eine Teilantwort besteht die gesamte Reihe nicht, und die Kana-Selbstprüfung ist bei der Sammelkarte nicht verfügbar. Direkt danach folgen bereits vorhandene Einzelkarten für 6–10. Die neue Vorbereitung löst nicht nachweislich jede kognitive Belastung: Anfänger-Erprobung bleibt offen. Eine künftig eigenständige Aufteilung der Prüfkarte würde eine separate Aufgaben-/Fortschrittsentscheidung erfordern; in diesem Paket keine neue ID oder Migration.',
      'Keine Änderung von Lektions-/Kartenidentitäten, XP, Reihenfolge, Kursrevision 11, Android FLOW_REVISION 2 oder Speicherschema. Alte Sessions bleiben an ihrer erreichten Aufgabe. Windows behält Verstehen und freiwilliges Sprechen, Android den bestehenden Pflichtablauf mit gekennzeichneter kurzer Kana-Selbstprüfung. Stimmen, Lehrer, Animationen, Modelle, Gesprächscode und Update-Sicherheit bleiben erhalten.',
      '## Gesprächsbezug und ehrliche Grenzen',
      'Drei automatisch geprüfte Wochenendwege: Film → Samstag → 10 Uhr vormittags → Bahnhof; Park → Sonntag → 14 Uhr → Cafévorplatz; Café → Samstag → 15 Uhr → Bahnhof. Die vorbereiteten Erklärungen behandeln die Servicefragen, Tag-/Uhrzeit-/Ortswahl und die zusammengesetzte Abschlussbestätigung. Die Szene unterstützt nur ihre vorhandenen Optionen. Eine andere sprachlich mögliche Zeit oder Aktivität ist dadurch nicht automatisch eine richtige Szenenantwort. Keine neue Engine, kein Windows-Gesprächsraum.',
      'Die Cafészene bleibt bei Bestellungen ohne Mengenwort und Größen S/klein oder L/groß. `コーヒーをひとつください` und `エムサイズでおねがいします` bleiben außerhalb der jeweiligen vorbereiteten Routen. Tests prüfen Ablehnung ohne Fortschritt und die vorhandene Rückmeldung über die Szenengrenze; kein Aussprachefehler wird daraus abgeleitet. Danach kann eine passende Antwort den gleichen Gesprächsweg fortsetzen. Kurslektionen mit Menge und M bleiben ausdrücklich zusätzliche Übungen.',
      '## Einordnung der Prüfungen',
      'Erfassung: alle Kursdaten und Analysebeziehungen. Eigene sprachliche Durchsicht: die genannten 25 Lektionen mit Beispielen, Lesungen, Näherungslautung und Aufgaben sowie der Zahlen-Grenzfall. Struktur-/Softwareprüfungen: `tests/test_package4.py`, `mobile/tests/package4.test.mjs`, native/basierte UI-Prüfungen und die bestehende vollständige Suite. Tatsächlich ausgeführte Ergebnisse, Buildstände und Aussagegrenzen stehen in `TESTBERICHT_11.0.6_TEST.md`; die öffentlichen Downloads anschließend in `VEROEFFENTLICHUNG_11.0.6_TEST.md`. Menschliche Fachprüfung, Anfänger-Erprobung, echte Mikrofon-/Hörtests und frisches Windows sind nicht durchgeführt.',
      'Punktueller Primärquellenabgleich: [Japan Foundation Irodori Starter Lektion 9](https://www.irodori.jpf.go.jp/assets/data/starter/pdf/X_L09.pdf), S. 1, 8 und 16–17, für Stundenlesungen, Wochentage, Zeitgrenzen und Terminantworten. Eigene Lehrtexte und Beispiele; keine Übernahme kompletter Übungen und keine externe Vollvalidierung. Der PDF-Abruf zu Lektion 12 schlug fehl und zählt nicht als Prüfung.',
      '## Konkrete sprachliche Unsicherheiten',
      '| Stellen | Noch von Menschen zu prüfen |\n| --- | --- |\n| `12:0:4` | Entlastung durch Zweiergruppen bei echten Anfängern; die Gesamtaufgabe bleibt lang. |\n| `12:1:2` | Soziale Angemessenheit einer Altersfrage je Gesprächssituation. |\n| `v11:people-age:4`, `v11:clock-minutes:2` | Priorisierung der Lesungsvarianten mit ju/j i und Verständlichkeit der Näherungslautung; bestehende Sprechvarianten nicht erweitert. |\n| `v11:reply-invites:1–4`, `v11:appointments:3–4` | Natürlichkeit und Stärke indirekter Absagen; keine universelle Bedeutung von だいじょうぶ. |\n| `v11:messages:0–3` | Register im konkreten beruflichen Verhältnis und Natürlichkeit der Änderungsbitte. |\n| `v11:dialog-weekend:0–4` | Natürlichkeit des ganzen Gesprächs und tatsächliches Verstehen seiner Ansagen beim Hören. |\n| `v11:read-plan:4`, `v11:read-message:3` | Ob lokale Erklärung von だったら/なら für Anfänger ausreicht; keine vollständige Behandlung aller Konditionalnuancen. |\n| Alle 123 Karten | Deutsche Näherungsaussprache, Natürlichkeit und Hörverständnis sind nicht muttersprachlich oder mit echten Aufnahmen abgenommen. |',
      '## Zuordnung Befund Kennung Änderung Prüfung',
      '| Position | Lektions-ID | Karten-IDs | Ausgangsbefund und Änderung | Konkrete Prüfung |\n| --- | --- | --- | --- | --- |']
    for key in GUIDES:
        l=raw[key][0];g=l['study_guide'];end=len(l['cards'])-1
        out.append(f'| {order.index(key)+1} | `{key}` | `{key}:0` bis `{key}:{end}` | Explizites Vorwissen und begründete Fehlantworten fehlten; {l["goal"]} | Voraussetzungen früher im Lernweg; jede Kartenlösung/Fehlantwort und Altprofil; sichtbare Hilfe ohne Freigabe. |')
    for key in GUIDES:
        l=raw[key][0];g=l['study_guide']
        out.append(f'## {order.index(key)+1} {l["title"]}\n\nStabile ID: `{key}`. {len(l["cards"])} vorhandene Karten. Lernziel: {l["goal"]}\n\nVoraussetzungen: '+', '.join(f'`{p}`' for p in g['prerequisites'])+'.\n\n'+'\n\n'.join(g['points'])+'\n\nAbruf: '+g['recall']+'\n\nSpätere Wiederaufnahme: '+', '.join(f'`{p}`' for p in g['retrieves'])+'.')
        out.append('| Stabile Karten-ID | Erhaltener Zieltext | Änderung der Anwendung / Rückmeldung |\n| --- | --- | --- |')
        for i,c in enumerate(l['cards']):
            q=c['detail']['scenario'];kind='Gezielte Anwendungsfrage' if (key,i) in APPLICATIONS else 'Erhaltene Leseverständnisfrage' if (key,i) in READ_FEEDBACK else 'Erhaltene Zuordnung mit ausdrücklichem Kartenbezug'
            out.append(f'| `{key}:{i}` | {c["jp"]} | {kind}: {q["question"]} Alle {len(q["wrong"])} falschen Auswahlwerte einzeln begründet. |')
    return re.sub(r'(?m)(\|[^\n]*\|)\n\n(?=\|)', r'\1\n', '\n\n'.join(out)).replace('mit ju/j i', 'mit ju/ji')
